---
title: "Reproducibility Report for Study X by Sample & Sample (20xx, Psychological Science)"
author: "Reproducibility Project Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

[No abstract is needed.]  Each reproducibility project will have a straightforward, no frills report of the study and reproducibility results. These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of your attempt to reproduce the results. Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for your reproducibility attempt, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  

Tim Sainburg's 2025 paper includes a breadth of modern techniques and analysis used in the Gentner Lab, making it a useful paper to simulate in order to familiarize myself with pertinent concepts and data. I will be simulating behavioral data from a two-alternative choice task (2AC) where the choices are modulated by the reliablilty of an auditory primer cue. This simulation will peak my interest into sensory systems while allowing me to work with real data and get experience analyzing it. 

For this project, I will need to simulate a new data set, clean it to calculate the necessary analytic points (such as change in inflection point), create a linear mixed effects model, and create a 2 distribution histogram (figure 3e in the original paper). I believe that this will be an adequate challenge because it will be a large dataset and I do not have any experience with linear mixed effects models. I will need to ensure that I am cleaning and analyzing such a large dataset accurately and take the necessary steps to understand linear mixed effects models. Although the data is not available in this paper, it is available in another paper (Gorman et al 2026) that analyzes the same dataset, and is available from internal documents in the Gentner lab, making to possible to simulate an accurate representation of the data. 


### Links

Project repository (on Github): https://github.com/willhammond03/sainburg2026.git

Original paper (as hosted in your repo): https://doi.org/10.1038/s41593-025-01899-1 

## Methods

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study. 

### Differences from original study

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.


### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
